on:
  release:
    types: [created]
    
jobs:
  release:
    name: Release and publish
    runs-on: ubuntu-latest
    steps:

      # Setup prereqs
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm install -g vsce
      
      # Create and publish build to Marketplace
      - name: Publish to Marketplace
        run: vsce publish -p $PUBLISHER_TOKEN
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}

      # Create and publish build to OpenVSX
      - name: Publish to Open VSX
        run: npx ovsx publish -p ${{ secrets.OPENVSX_TOKEN }}
        